### ISSUE TITLE
Export doesn't support multi currency

### ISSUE THREAD

**Issue by gunneman** [EmicoEcommerce/Magento1TweakwiseExport#14]
Issue Brief
--
When creating an export, it doesn't support multiple currencies. You can only export the default currency from a storeview.

Environment
--
- [ ] PHP Version: (5.6|7.0|7.1) 7.1
- [ ] Magento Version: 1.9.4.3
- [ ] Magento Enterprise: (yes|no) no
- [ ] Tweakwise Export Version: latest
- [ ] Magento Deploy Mode: (production|development) production
- [ ] Third party modules: multiple

Steps to reproduce
--
1. Create an export.
2. Open the .xml feed in your favorite text editor.
3. Look up a random product within a multi currency storeview.
4. Notice that you only have the price in the default currency and not both.

Actual result
--
1. Only default currency get's exported.

Expected result
--
List the expected results as a bullet list of expectations
- [ ] All available currencies get exported.

**Comment by edwinljacobs** [comment]
Hi

After some consideration it has been decided that this will not be implemented. Therefor I will close this issue.

With kind regards
