### ISSUE TITLE
Tag release compatible with the latest release of the Emico_Tweakwise module

### ISSUE THREAD

**Issue by aadmathijssen** [EmicoEcommerce/Magento1TweakwiseExport#5]
Later versions of the Emico_Tweakwise module contain the method `Emico_Tweakwise_Model_UrlBuilder_Strategy_PathStrategy::getSlugAttributeMapper`, which returns an instance of `Emico_TweakwiseExport_Model_SlugAttributeMapping`.

However, currently there is no tagged release of the Emico_TweakwiseExport that contains this class.

Could you please tag a release such that there is a least one official version of Emico_TweakwiseExport that can be used with the Emico_Tweakwise module?

Thanks.

**Comment by edwinljacobs** [comment]
Hello,

So the following happened, tag 1.11.3 of https://github.com/EmicoEcommerce/Magento1Tweakwise contained code, namely the url builder // slugifyer part, which after some consideration was not deemed ready for production sites. Hence that feature is removed in https://github.com/EmicoEcommerce/Magento1Tweakwise tag 1.11.4

We are sorry for the confusion and not correctly releasing the updates. The fixes made to ensure a faster category filter rendering are present in version 1.11.4.

**Comment by aadmathijssen** [comment]
Thanks for clarifying this and for releasing a new version of the Emico_Tweakwise module.

So v1.11.4 of the Emico_Tweakwise module should be used with version v2.2.1 of the Emico_TweakwiseExport module, right?

**Comment by edwinljacobs** [comment]
Yes that is the case.
